# Generated by Django 3.1.4 on 2020-12-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_auto_20201220_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='iva',
            new_name='igv',
        ),
    ]
