# Generated by Django 3.1.4 on 2020-12-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_auto_20201220_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacen',
            old_name='iva',
            new_name='igv',
        ),
    ]
